spring:
  datasource:
    url: jdbc:postgresql://${PGHOST}:${PGPORT}/${PGDATABASE}
    username: ${PGUSER}
    password: ${PGPASSWORD}
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    initialization-mode: always
    continue-on-error: true
  kafka:
    bootstrap-servers: kafka:9092
  consumer:
    bootstrap-servers: kafka:9092