token:
  aes: yfUlESNWLkXxc+zPosFMFTqIALPaeiHvayLwJjKy9w0=
  signing:
    keyAccess: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    timeAccess: 7200000
    #timeAccess: 120000 #2 минуты
    keyRefresh: 53A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A7532785553A73E5F1C4E0A2D3B5F2D784E6A1B423D6F247D1F6E5C3A596D635A75327855
    timeRefresh: 2592000000
    #timeRefresh: 300000 #5 минут

spring:
#  profiles:
#    active: dev
  application:
    name: BrusnikaCoworking
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        jdbc:
          time_zone: Asia/Yekaterinburg
#  jackson:
#    time-zone: Asia/Yekaterinburg

  datasource:
    url: jdbc:postgresql://${PGHOST:localhost}:${PGPORT:6432}/${POSTGRES_DB:brusnika}?options=-c%20TimeZone=Asia/Yekaterinburg
    username: ${POSTGRES_USER:postgres}
    password: ${POSTGRES_PASSWORD:postgres}
    driver-class-name: org.postgresql.Driver
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    initialization-mode: always
    continue-on-error: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: coworking.brusnika@gmail.com
    password: cgbd ywxl rvpg fdqn
    properties:
      mail:
        smtp:
          auth: true
        smtp.starttls.enable: true
  kafka:
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost}:9092
      properties:
        spring:
          json:
            add:
              type:
                headers: false
    consumer:
      bootstrap-servers: ${KAFKA_BOOTSTRAP:localhost}:9092
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.ByteArrayDeserializer
      properties:
        spring:
          json:
            add:
              type:
                headers: false
      # Увеличение таймаутов
      socket.connection.setup.timeout.ms: 30000
      request.timeout.ms: 60000
      session.timeout.ms: 30000
      fetch.max.wait.ms: 500
      heartbeat.interval.ms: 3000

server:
  frontend-url: https://brusnikacoworking.netlify.app #нужен base front
#  frontend-url: http://localhost:5173
  notification-url: /notification #нужен на раздел уведомлений
#  port: 8080

# для запуска файла выполнить команду в терминале:
# docker compose up -d
# docker-compose restart